version: "3.8"

services:
  emby:
    image: emby/embyserver:latest
    restart: unless-stopped
    ports:
      - 8096:8096
    volumes:
      - /mnt/2tb/Docker/emby/data:/config
      - /mnt:/mnt:ro
    environment:
      - UID=1000
      - GID=1000
    networks: 
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.services.emby.loadbalancer.server.port=8096
      - homepage.group=Services
      - homepage.name=Emby
      - homepage.icon=emby.png
      - homepage.href=https://emby.$EXT_HOST
      - homepage.description=Media server
      - homepage.widget.type=emby
      - homepage.widget.url=https://emby.$EXT_HOST
      - homepage.widget.key=$API_KEY

networks:
  frontend:
    external: true
